 SELECT SUBSTRING(SALES_DATE, 1, 10) AS SALES_DATE,
           PRODUCT_ID,
           USER_ID,
           SALES_AMOUNT
        FROM ONLINE_SALE
        WHERE Month(SALES_DATE) = 3
UNION
    SELECT SUBSTRING(SALES_DATE, 1, 10) AS SALES_DATE,
           PRODUCT_ID, 
           NULL AS USER_ID,
           SALES_AMOUNT
        FROM OFFLINE_SALE
        WHERE Month(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID